
# =========================================
# Stage 1: Build the Angular Application
# =========================================
ARG NODE_VERSION=10.9.0
ARG NGINX_VERSION=1.30-alpine

# Use a lightweight Node.js image for building (customizable via ARG)
FROM node:${NODE_VERSION} AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy package-related files first to leverage Docker's caching mechanism
COPY package.json *package-lock.json* ./

# Install project dependencies using npm ci (ensures a clean, reproducible install)
RUN --mount=type=cache,target=/root/.npm npm ci

# Copy the rest of the application source code into the container
COPY . .

# Build the Angular application
RUN npm run build

# =========================================
# Stage 2: Prepare Nginx to Serve Static Files
# =========================================

 FROM alpine:3.19

 COPY --from=builder /app/dist/kanban-ui /src

 CMD ["sh", "-c", "cp -r /src/* /output/"]
